### PR TITLE
Update bitflags to 1.0 and bump version

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by bvssvni** [comment]
cc @nwin

**Comment by bvssvni** [comment]
@Eijebong It looks good, except for small thing: Do you think `Transformations` should be used when that's more custom to use on iterators in Rust?

**Comment by Eijebong** [comment]
Not sure I understand your question. Do you want me to rename that enum to something else ?

**Comment by bvssvni** [comment]
I was thinking about calling it `Transformation` instead of `Transformations`.

**Comment by Eijebong** [comment]
Oh... I don't think I ever saw a bitflags struct that wasn't a plural, so I think it's better to stick with `Transformations`.

**Comment by bvssvni** [comment]
OK. Merging.

**Pull request merged**
