### PR TITLE
Update bitflags 0.7 -> 0.9

### PR DESCRIPTION
**Pull request by budziq**
Hi,
We've encountered a dependency problem in https://github.com/brson/rust-cookbook/pull/192 due to outdated bitflags version here.

### CODE REVIEW

**Comment by bvssvni** [comment]
Can you bump the library version to 0.8.0?

**Comment by budziq** [comment]
@bvssvni  done :)

**Comment by bvssvni** [comment]
Nice! Merging.

**Comment by budziq** [comment]
Thanks!

**Comment by budziq** [comment]
Hi, @bvssvni 

This would be awesome if this version of `image-png` v0.8.0 could be released to crates.io :smile:

A version of parent `image` would also have to be updated to use this release of `image-png` to solve our buildbreak on rust-cookbook.

I'll gladly make the PR against `image` to update the dependency.

**Comment by bvssvni** [comment]
Published. I'll update `image`.

**Comment by budziq** [comment]
Wow thanks!

**Pull request merged**
